# Generated by Django 5.0.3 on 2024-04-08 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_contributor_project"),
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(
                through="authentication.Contributor", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
