# Generated by Django 5.0.3 on 2024-04-08 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_project_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="project",
            table=None,
        ),
    ]
