# Generated by Django 5.0.3 on 2024-04-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_project_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "low"), ("MEDIUM", "medium"), ("HIGH", "high")],
                default="",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="tag",
            field=models.CharField(
                choices=[
                    ("To Do", "to do"),
                    ("In Progress", "in progress"),
                    ("Finished", "finished"),
                ],
                default="",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("front-end", "front-end"),
                    ("Back-end", "back-end"),
                    ("iOs", "iOs"),
                    ("android", "android"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
