# Generated by Django 5.0.4 on 2024-04-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_issue_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "low"), ("MEDIUM", "medium"), ("HIGH", "high")],
                default="",
                max_length=15,
            ),
        ),
    ]
