# Generated by Django 5.0.3 on 2024-04-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(default=False, verbose_name="contactable"),
        ),
        migrations.AddField(
            model_name="user",
            name="can_data_be_shared",
            field=models.BooleanField(default=False, verbose_name="shareable"),
        ),
    ]
