# Generated by Django 5.0.4 on 2024-04-15 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="issue",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.issue",
            ),
        ),
    ]
