# Generated by Django 5.0.3 on 2024-04-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_remove_user_groups_remove_user_user_permissions_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birth_date",
        ),
    ]
