# Generated by Django 5.0.4 on 2024-04-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_rename_id_user_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="id",
        ),
    ]
