# Generated by Django 5.0.3 on 2024-04-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=40, unique=True, verbose_name="username"),
        ),
    ]
