# Generated by Django 5.0.3 on 2024-04-04 22:35

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(
                null=True, validators=[authentication.models.validate_age]
            ),
        ),
    ]
